dist: trusty
language: generic

notifications:
  email: false

env:
  global:
    - secure: "CdXW/R5M+QipYa13LaQR4qQuDOEXP1RHETxntinJSvfr7bPF7ysqXZOsnBsm+ThYhHqilgt3qsbQ9dZojxk2zFuhR8jodyzMLl5et2PzKuMZTUxcn+dho8JJmd0kt6Lz17QD3mnk3FX6dl0ZBsFd83l0XRAzSMu6s7+VuVqckMPIagQhxxlNGR4K6H3em1OIpzlPLEA4t33eVcPyyQOZstDZd64ZVH+EMt+XVClmk2J77SZ9s39WDdYipo+9wJr8YvYYka4uPBH2XHISzIv7Pgsbje7bx7EzaU2gJWfcMdIKEV+6iUonuO+zKqWmgzKCY0UGdu9Gc9qsZkH45rYXb6IezbTL9iuFk63YxokKWUwAhyHJhX9ixGB7iYCni2ZHaF7axREQEo4/X80eEW6ACCFeeR7bgRoHURQrAJ4zDOSjRO3icbNpkN2MF91pP6v9NFPzLomfnfrgt4tG/9b+iA4dkyKGO6a4br021OwltPrEepDrtW12Dcv07CbAYyuQg8B/ygjXN9tsSjvAzX3sBMBtIEE6kDplOEVVt6oP6GfQYrLUDFAhtW4wRCkaF0snkRkNy0uGYuYN7SMqzSUkCg9+9p1DkUQf+/YweLCXai89iofefkFVIQ8qxSEjtRjsxG/yEa9K8kdXRikLuzt2+Th3db6wkJiM62z+p7FnESI="  # DOCKER_USERNAME
    - secure: "JcM+nm8PEA0W2p6ckqVmIof2VEH98NADXogmcHC8S4+xlw60WRcWt0FS32BSWlLWvjNbci1v55e7r7B5QtKVavP59KM/P7/TwOGtO0nsJnizPSdNPPV4GamrAUVzHvFfv5VjS3eBM2jqOsx17cl8mbExdqBehL1o0pLlvk7JDSyPkyU/29Z/l/J6ls3k5wWU5kCZx+Uotni15TqBfeoMm7CEx4ykJLo/6N5AN2nP1nyXzs6lo86zqNoka6wihS/3fT4nAL/uVgP327EM2bRe0tkUC7sXsVcaS3RzuuSQRYGsizTutBcL5sis/vCLBdphf3SzYkmbHTeRW1mjRseHCZS1ktsqYZn4HGpqFJMs+qQX4Eqgg4Y/6oqBtxaAokwhaF3vf2Q9/Gztf9NS2dIMXM5mPF8FL7rxzp4z1YQPvTXx7zzirTqVczDh24MbRHglvcn8Mv9+B7cHneyu34AkpcQjjQvsX9OoeRhY/19bIE+5nn/lgqIYWxEbWq7EYfjHpU1mT1v/C6+BM+GwZ85eiC+UYCw2+kXuxGx1/Ha7xvwf815ehHL4d9KPH4chlvPO6GJE2YE0/z9NbIVymCkIaT/bCSLMsI+AZofs9Rv8O50hJD5jg9XE6JQaqTxumj90kSOB2uv7blhy6qsk+fVqWnJoUC9GVQj3CDa9oD4Gjus="  # DOCKER_PASSWORD
  matrix:
    - DISTRO=centos7
    - DISTRO=bionic

script: bash scripts/docker-build.sh

deploy:
  provider: script
  script: bash scripts/docker-tag-and-push.sh
  on:
    tags: true
