dist: trusty
language: generic

notifications:
  email: false

env:
  global:
    - secure: "CdXW/R5M+QipYa13LaQR4qQuDOEXP1RHETxntinJSvfr7bPF7ysqXZOsnBsm+ThYhHqilgt3qsbQ9dZojxk2zFuhR8jodyzMLl5et2PzKuMZTUxcn+dho8JJmd0kt6Lz17QD3mnk3FX6dl0ZBsFd83l0XRAzSMu6s7+VuVqckMPIagQhxxlNGR4K6H3em1OIpzlPLEA4t33eVcPyyQOZstDZd64ZVH+EMt+XVClmk2J77SZ9s39WDdYipo+9wJr8YvYYka4uPBH2XHISzIv7Pgsbje7bx7EzaU2gJWfcMdIKEV+6iUonuO+zKqWmgzKCY0UGdu9Gc9qsZkH45rYXb6IezbTL9iuFk63YxokKWUwAhyHJhX9ixGB7iYCni2ZHaF7axREQEo4/X80eEW6ACCFeeR7bgRoHURQrAJ4zDOSjRO3icbNpkN2MF91pP6v9NFPzLomfnfrgt4tG/9b+iA4dkyKGO6a4br021OwltPrEepDrtW12Dcv07CbAYyuQg8B/ygjXN9tsSjvAzX3sBMBtIEE6kDplOEVVt6oP6GfQYrLUDFAhtW4wRCkaF0snkRkNy0uGYuYN7SMqzSUkCg9+9p1DkUQf+/YweLCXai89iofefkFVIQ8qxSEjtRjsxG/yEa9K8kdXRikLuzt2+Th3db6wkJiM62z+p7FnESI="  # DOCKER_USERNAME
    - secure: "dTqlgb4V4OJhbIpyFDC5YoLV5EuOl/ZUQ/PAt7cjKGg6kjhEljBOqMbgP/lSVeMQq6FH8XVEw3LlDn4ItuZV9fEL1VLjg7VIJpWWG5WiwhAzk2NFENs9E50uPsbpobda42DbAfCQXpXqDL49/GpaedA5qpbEguaDxLQLQV2OME4iQJG0L2gY763qgmQnE5a7AW4NwGj6s6GHOgzUOKF7mAhV/wFBFEb5LhNweMWynmtycV0dxl68kTSnO219s/uGhSOkmyD8Cx1zcyWG7Sls9SFZPBtoTd9Z03rl4XgPs++XgrJpWaAn51UdpAFMuekNfmsZVaCgQ3WyU+sj9qMs3QHHKWl8qN+9tCL+NU7OVzok1hGJk9APCTK0SaJhg3syA6kVRhqJg7r0EkvB1MKVt6b66TwDSw6PuJ/BJMC4OY16E7+uZEbZwnE/GxK2ko9uyv8CQ8EknDpL1Yce2j1ypFsgpTNljMBp8p4GhjoAJMt/G9HNVxh9yEcmwnYqxJ+w6TRqNmy+NTOFmJKlb69hE6TX4oc/7k/SgL6pzXUyKtGhnTCOlZRBZ//IGaxkzx1utgdqjqm8lukfKPs0ZFu5gZ0W8d3jvKpNVLOXcb5xOi0yc9+tY5kDJWgsXu09sY9TB1YVag5kmDc8YYAQACnantzmCHhwLmpwoJWL+9mStY0="  # DOCKER_PASSWORD
  matrix:
    - DISTRO=centos7
    - DISTRO=bionic

script: bash scripts/docker-build.sh

deploy:
  provider: script
  script: bash scripts/docker-tag-and-push.sh
  on:
    tags: true
